[project]
site_name = "Credit Scoring MLOps"
site_description = "Support de soutenance : modèle, API, application, monitoring et déploiement MLOps."
site_author = "Olivier"
docs_dir = "docs"
site_dir = "site"

nav = [
  {"Contexte" = "index.md"},
  {"Conception du modèle" = "model.md"},
  {"API FastAPI" = "api.md"},
  {"App Prédiction" = "prediction.md"},
  {"App Monitoring" = "monitoring.md"},
  {"CI/CD" = "cicd.md"},
  {"Docker et Hugging Face" = "deployment.md"},
  {"Structure du dépôt" = "depot.md"},
  {"Démo soutenance" = "demo.md"}
]

[project.theme]
features = [
  "navigation.tabs",
  "navigation.sections",
  "navigation.path",
  "toc.follow",
  "content.code.copy"
]
