[project]
site_name = "Credit Scoring MLOps"
site_description = "Support de soutenance : modèle, API, application, monitoring et déploiement MLOps."
site_author = "Olivier"
docs_dir = "docs"
site_dir = "site"
extra_css = [
  "stylesheets/presentation.css"
]


nav = [
  {"01. Contexte" = "index.md"},
  {"02. Conception du modèle" = "02_model.md"},
  {"03. API FastAPI" = "03_api.md"},
  {"04. App Prédiction" = "04_prediction.md"},
  {"05. App Monitoring" = "05_monitoring.md"},
  {"06. CI/CD et Déploiement" = "06_cicd.md"},
  {"07. Structure du dépôt" = "07_depot.md"}
]

[project.theme]
features = [
  "navigation.tabs",
  "navigation.sections",
  "navigation.path",
  "toc.follow",
  "content.code.copy"
]
language = "fr"
