# config/exp_xgboost.yaml
experiment_name: "Credit_Scoring"

load: "baseline"
preprocess: "linear"
model: "xgboost"

hyperparameters:
  n_estimators: 100
  learning_rate: 0.08
  max_depth: 6
  min_child_weight: 2
  scale_pos_weight: 11.5   # Ratio of negative class over positive class instances