# config/exp_catboost.yaml
experiment_name: "Credit_Scoring"

load: "baseline"
preprocess: "tree"         # Les modèles à base d'arbres supportent mieux les valeurs manquantes/catégorielles
model: "catboost"

hyperparameters:
  iterations: 1000         # Nombre d'arbres
  learning_rate: 0.05      # Taux d'apprentissage classique
  depth: 6                 # Profondeur des arbres (entre 4 et 10)
  l2_leaf_reg: 3.0         # Régularisation pour éviter l'overfitting
  auto_class_weights: "Balanced" # Gestion du déséquilibre de classe
  od_type: "Iter"          # Type d'arrêt précoce (Overfitting Detector)
  od_wait: 50              # Nombre d'itérations sans amélioration avant arrêt