name: CD

on:
  push:
    branches: [main]

jobs:
  deploy-hf-space:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Build Docker image (validation)
      #  run: docker build -t credit-scoring .

      - name: Push to Hugging Face Space
        uses: huggingface/spaces-actions@v1
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repository : ${{ secrets.HF_USERNAME }}/credit-scoring